### ISSUE TITLE
Feature request: mapper qm

### ISSUE THREAD

**Issue by kaleko** [breakone9r/mmpkg#14]
Auto go to nearest qm!

**Comment by breakone9r** [comment]
Well, you could fairly easily implement this on your own, using existing code in my package.

Specifically, you could create an alias to call the function mmpkg.setFlags(room#,"questmaster") for any rooms with a questmaster in them. You'd need to do this is every QM room.

This would create the flag "questmaster" for these rooms. at which point you could use > mapper room find questmaster and it'll show you rooms in your area that are questmasters. This is the most time-consuming part of the feature, and updating your map would remove all existing QM info, because it's not something originally considered, but unless you're completely reinstalling, you probably wouldnt need to update the map.

You could then also create an alias to call the function mmpkg.mfind("questmaster", true, true) This would find the closest QM and then automatically speedwalk to it. (The function works like this, find all rooms that match the flag provided with variable 1, and if variable 2 is true, then automatically speedwalk to it, and variable 3 determines if it's only just searches in the current zone, or the entire world, true will search only the local zone.)

All of this is to say that it could be done. I just, honestly have no desire to play MM for the forseeable future, although I do chat on the discord from time to time.

If you do implement this locally, feel free to create a merge request here. If you modify your map as mentioned above, I'll be glad to replace the map on the gh server.

**Comment by Hezkezl** [comment]
Loaaaads easier to just use the aliases that're already part of the package. Runeqm/keepqm/sigqm/xavqm/etc.

Less characters to type than 'mapper qm' :D

**Comment by breakone9r** [comment]
Exactly. :)
